# Generated by Django 2.1.2 on 2019-05-27 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('name_az', models.CharField(max_length=256, null=True)),
                ('name_ru', models.CharField(max_length=256, null=True)),
                ('description', models.TextField(blank=True, max_length=10000, null=True)),
                ('description_az', models.TextField(blank=True, max_length=10000, null=True)),
                ('description_ru', models.TextField(blank=True, max_length=10000, null=True)),
            ],
        ),
    ]
