# Generated by Django 2.1.2 on 2019-04-25 18:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ata_name', models.CharField(max_length=30, null=True)),
                ('image', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='profile_pics')),
                ('qan_qrupu', models.CharField(max_length=30, null=True)),
                ('gender', models.CharField(max_length=30, null=True)),
                ('city', models.CharField(max_length=30, null=True)),
                ('borndate', models.DateField(blank=True, null=True)),
                ('konullu_sigorta_com', models.CharField(blank=True, max_length=30, null=True)),
                ('konullu_sigorta_id', models.CharField(blank=True, max_length=30, null=True)),
                ('icbari_sigorta_com', models.CharField(blank=True, max_length=30, null=True)),
                ('icbari_sigorta_id', models.CharField(blank=True, max_length=30, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
