# Generated by Django 2.1.2 on 2019-02-13 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190212_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ata_name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
