# Generated by Django 2.1.2 on 2019-03-03 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('MRK', 'Merkez'), ('FLL', 'filial')], max_length=25, null=True)),
                ('name', models.CharField(max_length=256)),
                ('address', models.CharField(max_length=256)),
                ('description', models.TextField(max_length=10000, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lon', models.FloatField(blank=True, null=True)),
                ('filial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filiallar', to='clinic.Clinic')),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='clinic.Clinic')),
            ],
        ),
        migrations.CreateModel(
            name='Prices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qiymet', models.CharField(max_length=64)),
                ('klinika', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.Clinic')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.Service')),
            ],
        ),
        migrations.CreateModel(
            name='Sertifikat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sertifikatlar', to='clinic.Clinic')),
            ],
        ),
        migrations.AddField(
            model_name='clinic',
            name='services',
            field=models.ManyToManyField(related_name='relate_name_services', through='clinic.Prices', to='service.Service'),
        ),
    ]
