# Generated by Django 2.1.2 on 2019-05-27 11:50

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='xidmetler',
            field=mptt.fields.TreeManyToManyField(blank=True, null=True, related_name='relate_name_xidmetler', through='clinic.XidmetlerPrices', to='service.Xidmat', verbose_name='Xidmətlər və qiymətləri'),
        ),
        migrations.AlterField(
            model_name='xidmetlerprices',
            name='xidmet',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qiymetler', to='service.Xidmat', verbose_name='Xidmətin Adı'),
        ),
    ]
