# Generated by Django 2.1.2 on 2019-04-25 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_auto_20190425_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='image',
            field=models.ImageField(blank=True, default='defaultclinic.png', null=True, upload_to='', verbose_name='Profil Şəkli'),
        ),
    ]
