# Generated by Django 2.1.2 on 2019-05-27 11:55

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_auto_20190527_0450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='diaqnostikalar',
            field=mptt.fields.TreeManyToManyField(blank=True, null=True, related_name='relate_name_diaqnostikalar', through='clinic.DiaqnostikalarPrices', to='service.Diaqnostika', verbose_name='Diaqnostik Xidmətlər və qiymətləri'),
        ),
        migrations.AlterField(
            model_name='diaqnostikalarprices',
            name='diaqnostika',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qiymetler', to='service.Diaqnostika', verbose_name='Diaqnpstik Xidmətin Adı'),
        ),
    ]
