# Generated by Django 2.1.2 on 2019-02-13 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_auto_20190213_0723'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
