# Generated by Django 2.1.2 on 2019-05-05 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0003_auto_20190425_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='city',
            field=models.CharField(blank=True, choices=[('Bakı', 'Bakı'), ('Sumqayıt', 'Sumqayıt')], max_length=25, null=True, verbose_name='Şəhər'),
        ),
    ]
