# Generated by Django 2.1.2 on 2019-02-18 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0003_clinic_image1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic_branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('address', models.CharField(max_length=256)),
                ('description', models.TextField(max_length=10000, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='clinic.Clinic')),
            ],
        ),
    ]
