# Generated by Django 2.1.2 on 2019-03-03 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0003_auto_20190303_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='services',
            field=models.ManyToManyField(blank=True, null=True, related_name='relate_name_services', through='clinic.Prices', to='service.Service'),
        ),
    ]
