# Generated by Django 2.1.2 on 2019-06-10 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0004_auto_20190610_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='city',
            field=models.CharField(blank=True, choices=[('Bakı', 'Bakı'), ('Sumqayıt', 'Sumqayıt'), ('Gəncə', 'Gəncə'), ('Qəbələ', 'Qəbələ')], max_length=25, null=True, verbose_name='Şəhər'),
        ),
    ]
