# Generated by Django 2.1.2 on 2019-02-20 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xidmetler', '0001_initial'),
        ('clinic', '0004_clinic_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='xidmetler',
            field=models.ManyToManyField(related_name='xidmetler', to='xidmetler.Xidmetler'),
        ),
        migrations.AddField(
            model_name='clinic_branch',
            name='xidmetler',
            field=models.ManyToManyField(related_name='branchxidmetler', to='xidmetler.Xidmetler'),
        ),
    ]
