# Generated by Django 2.1.2 on 2019-05-05 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0005_auto_20190504_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='bazar',
            field=models.BooleanField(blank=True, null=True, verbose_name='Bazar işləyir'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='senbe',
            field=models.BooleanField(blank=True, null=True, verbose_name='Şənbə işləyir'),
        ),
    ]
