# Generated by Django 2.1.2 on 2019-06-10 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0005_auto_20190610_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Klinikalar', to='clinic.City', verbose_name='Şəhər'),
        ),
    ]
