# Generated by Django 2.1.2 on 2019-06-11 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0006_auto_20190610_1511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinic',
            name='city',
        ),
    ]
