# Generated by Django 2.1.2 on 2019-05-13 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0006_auto_20190504_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='descriptionmetadiaqnostika',
            field=models.TextField(blank=True, max_length=256, null=True, verbose_name='Diaqnostika Kard Məlumatı'),
        ),
    ]
