# Generated by Django 2.1.2 on 2019-02-20 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0006_auto_20190220_0620'),
    ]

    operations = [
        migrations.RenameField(
            model_name='xidmetler_qiymet',
            old_name='xidmetler',
            new_name='xidmetlers',
        ),
    ]
