# Generated by Django 2.1.2 on 2019-05-13 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0007_clinic_descriptionmetadiaqnostika'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='descriptionmetadiaqnostika_az',
            field=models.TextField(blank=True, max_length=256, null=True, verbose_name='Diaqnostika Kard Məlumatı'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='descriptionmetadiaqnostika_ru',
            field=models.TextField(blank=True, max_length=256, null=True, verbose_name='Diaqnostika Kard Məlumatı'),
        ),
    ]
