# Generated by Django 2.1.2 on 2019-06-11 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0007_remove_clinic_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='name_az',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Şəhər adı'),
        ),
        migrations.AddField(
            model_name='city',
            name='name_ru',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Şəhər adı'),
        ),
    ]
