# Generated by Django 2.1.2 on 2019-03-03 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0009_xidmatlar'),
        ('clinic', '0008_auto_20190303_1430'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qiymet', models.CharField(max_length=64)),
                ('klinika', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.Clinic')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.Xidmatlar')),
            ],
        ),
        migrations.AddField(
            model_name='clinic',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='relate_name_services', through='clinic.Prices', to='service.Xidmatlar'),
        ),
    ]
