# Generated by Django 2.1.2 on 2019-06-11 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0008_auto_20190611_0415'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Klinikalar', to='clinic.City', verbose_name='Şəhər'),
        ),
    ]
