# Generated by Django 2.1.2 on 2019-05-17 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0008_auto_20190512_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='diaqnostikalarprices',
            name='endirimli_qiymet',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Endirimli Qiymət'),
        ),
        migrations.AddField(
            model_name='xidmetlerprices',
            name='endirimli_qiymet',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Endirimli Qiymət'),
        ),
        migrations.AlterField(
            model_name='diaqnostikalarprices',
            name='qiymet',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Qiymət'),
        ),
    ]
