# Generated by Django 2.1.2 on 2019-02-20 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xidmetler', '0001_initial'),
        ('clinic', '0008_auto_20190220_0624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='xidmetler_qiymet',
            name='clinic',
        ),
        migrations.RemoveField(
            model_name='xidmetler_qiymet',
            name='xidmetlers',
        ),
        migrations.AddField(
            model_name='xidmetler_qiymet',
            name='qiymet',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='xidmetler_qiymet',
            name='xidmetler',
            field=models.ManyToManyField(related_name='xidmetler_qiymet', to='xidmetler.Xidmetler'),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='xidmetler',
            field=models.ManyToManyField(related_name='xidmetler', to='xidmetler.Xidmetler'),
        ),
    ]
