# Generated by Django 2.1.2 on 2019-05-17 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0009_auto_20190516_1717'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diaqnostikalarprices',
            name='endirimli_qiymet',
        ),
        migrations.RemoveField(
            model_name='xidmetlerprices',
            name='endirimli_qiymet',
        ),
        migrations.AddField(
            model_name='diaqnostikalarprices',
            name='endirim_faizi',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Endirim Faizi'),
        ),
        migrations.AddField(
            model_name='xidmetlerprices',
            name='endirim_faizi',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Endirim Faizi'),
        ),
    ]
