# Generated by Django 2.1.2 on 2019-02-20 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0010_auto_20190220_0656'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinic',
            name='xidmetler',
        ),
    ]
