# Generated by Django 2.1.2 on 2019-02-20 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0011_remove_clinic_xidmetler'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='xidmetler_qiymet',
            name='xidmet',
        ),
    ]
