# Generated by Django 2.1.2 on 2019-02-20 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0012_remove_xidmetler_qiymet_xidmet'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Xidmetler_qiymet',
        ),
    ]
