# Generated by Django 2.1.2 on 2019-03-03 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0012_auto_20190303_1459'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prices',
            name='klinika',
        ),
        migrations.RemoveField(
            model_name='prices',
            name='xidmet',
        ),
        migrations.RemoveField(
            model_name='clinic',
            name='xidmetler',
        ),
        migrations.DeleteModel(
            name='Prices',
        ),
    ]
