# Generated by Django 2.1.2 on 2019-03-03 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0015_auto_20190303_1513'),
        ('clinic', '0013_auto_20190303_1502'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaqnostikalarPrices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qiymet', models.CharField(max_length=64)),
                ('diaqnostika', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.Diaqnostikalar')),
                ('klinika', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.Clinic')),
            ],
        ),
        migrations.CreateModel(
            name='XidmetlerPrices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qiymet', models.CharField(max_length=64)),
                ('klinika', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.Clinic')),
                ('xidmet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.Xidmatlar')),
            ],
        ),
        migrations.AddField(
            model_name='clinic',
            name='diaqnostikalar',
            field=models.ManyToManyField(blank=True, related_name='relate_name_diaqnostikalar', through='clinic.DiaqnostikalarPrices', to='service.Diaqnostikalar'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='xidmetler',
            field=models.ManyToManyField(blank=True, related_name='relate_name_xidmetler', through='clinic.XidmetlerPrices', to='service.Xidmatlar'),
        ),
    ]
