# Generated by Django 2.1.2 on 2019-03-04 12:31

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0014_auto_20190303_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
