# Generated by Django 2.1.2 on 2019-03-04 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0015_auto_20190304_0431'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinic',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='clinic',
            name='lon',
        ),
        migrations.AddField(
            model_name='clinic',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='clinic',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
