# Generated by Django 2.1.2 on 2019-03-05 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0017_auto_20190304_0606'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='metro1',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='clinic',
            name='metro2',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
