# Generated by Django 2.1.2 on 2019-03-10 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0018_auto_20190305_0255'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='descriptionmeta',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
