# Generated by Django 2.1.2 on 2019-03-10 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0019_clinic_descriptionmeta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='descriptionmeta',
            field=models.TextField(blank=True, max_length=256, null=True),
        ),
    ]
