# Generated by Django 2.1.2 on 2019-03-21 10:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clinic', '0022_auto_20190319_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='wishlist',
            field=models.ManyToManyField(blank=True, related_name='clinicwishlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
