# Generated by Django 2.1.2 on 2019-04-03 12:01

from django.db import migrations, models
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0024_auto_20190325_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='cityy',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clinic',
            name='location2',
            field=location_field.models.plain.PlainLocationField(blank=True, max_length=63, null=True),
        ),
    ]
