# Generated by Django 2.1.2 on 2019-04-05 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0026_auto_20190403_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='metro1distance',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='clinic',
            name='metro2distance',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
