# Generated by Django 2.1.2 on 2019-04-17 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0027_auto_20190404_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='issaati1',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='clinic',
            name='issaati2',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='clinic',
            name='issaati3',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
