# Generated by Django 2.1.2 on 2019-04-17 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0028_auto_20190417_0601'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clinic',
            old_name='issaati1',
            new_name='bz_cm_issaati',
        ),
        migrations.RenameField(
            model_name='clinic',
            old_name='issaati2',
            new_name='bz_issaati',
        ),
        migrations.RenameField(
            model_name='clinic',
            old_name='issaati3',
            new_name='sn_issaati',
        ),
    ]
