# Generated by Django 2.1.2 on 2019-04-17 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0029_auto_20190417_0603'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clinic',
            old_name='bz_cm_issaati',
            new_name='be_cm_issaati',
        ),
    ]
