# Generated by Django 2.1.2 on 2019-04-19 23:21

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0030_auto_20190417_0614'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='address_az',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='clinic',
            name='address_ru',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='clinic',
            name='description_az',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clinic',
            name='description_ru',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clinic',
            name='descriptionmeta_az',
            field=models.TextField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='clinic',
            name='descriptionmeta_ru',
            field=models.TextField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='clinic',
            name='metro1_az',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='clinic',
            name='metro1_ru',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='clinic',
            name='metro1distance_az',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='clinic',
            name='metro1distance_ru',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='clinic',
            name='metro2_az',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='clinic',
            name='metro2_ru',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='clinic',
            name='metro2distance_az',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='clinic',
            name='metro2distance_ru',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='clinic',
            name='name_az',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='clinic',
            name='name_ru',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
