# Generated by Django 2.1.2 on 2019-04-19 23:36

import ckeditor.fields
import clinic.widgets
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0031_auto_20190419_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='address',
            field=models.CharField(max_length=256, verbose_name='Klinika Ünvanı'),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='address_az',
            field=models.CharField(max_length=256, null=True, verbose_name='Klinika Ünvanı'),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='address_ru',
            field=models.CharField(max_length=256, null=True, verbose_name='Klinika Ünvanı'),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='be_cm_issaati',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='BE - Cümə İş Saatı'),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='bz_issaati',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Bazar İş Saatı'),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Klinika Profil Məlumatı'),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='description_az',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Klinika Profil Məlumatı'),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='description_ru',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Klinika Profil Məlumatı'),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='descriptionmeta',
            field=models.TextField(blank=True, max_length=256, null=True, verbose_name='Klinika Kard Məlumatı'),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='descriptionmeta_az',
            field=models.TextField(blank=True, max_length=256, null=True, verbose_name='Klinika Kard Məlumatı'),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='descriptionmeta_ru',
            field=models.TextField(blank=True, max_length=256, null=True, verbose_name='Klinika Kard Məlumatı'),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='diaqnostikalar',
            field=models.ManyToManyField(blank=True, related_name='relate_name_diaqnostikalar', through='clinic.DiaqnostikalarPrices', to='service.Diaqnostikalar', verbose_name='Diaqnostik Xidmətlər və qiymətləri'),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='filial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filiallar', to='clinic.Clinic', verbose_name='Aid olduğu mərkəz klinika'),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Profil Şəkli'),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='location',
            field=clinic.widgets.LocationField(blank=True, max_length=255, verbose_name='Klinika Xəritədə Yeri'),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='metro1',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Yaxın Olduğu 1-ci Metro'),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='metro1_az',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Yaxın Olduğu 1-ci Metro'),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='metro1_ru',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Yaxın Olduğu 1-ci Metro'),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='metro1distance',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='1-ci Metroya olan Məsafə'),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='metro1distance_az',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='1-ci Metroya olan Məsafə'),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='metro1distance_ru',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='1-ci Metroya olan Məsafə'),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='metro2',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Yaxın Olduğu 2-ci Metro'),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='metro2_az',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Yaxın Olduğu 2-ci Metro'),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='metro2_ru',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Yaxın Olduğu 2-ci Metro'),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='metro2distance',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='2-ci Metroya olan Məsafə'),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='metro2distance_az',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='2-ci Metroya olan Məsafə'),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='metro2distance_ru',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='2-ci Metroya olan Məsafə'),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='name',
            field=models.CharField(max_length=256, verbose_name='Klinika Adı'),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='name_az',
            field=models.CharField(max_length=256, null=True, verbose_name='Klinika Adı'),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='name_ru',
            field=models.CharField(max_length=256, null=True, verbose_name='Klinika Adı'),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='phone',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Əlaqə Telefonu'),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='sn_issaati',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Şənbə İş Saatı'),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='type',
            field=models.CharField(blank=True, choices=[('MRK', 'Merkez'), ('FLL', 'filial')], max_length=25, null=True, verbose_name='Klinika Növü'),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='xidmetler',
            field=models.ManyToManyField(blank=True, related_name='relate_name_xidmetler', through='clinic.XidmetlerPrices', to='service.Xidmatlar', verbose_name='Xidmətlər və qiymətləri'),
        ),
        migrations.AlterField(
            model_name='diaqnostikalarprices',
            name='diaqnostika',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qiymetler', to='service.Diaqnostikalar', verbose_name='Diaqnpstik Xidmətin Adı'),
        ),
        migrations.AlterField(
            model_name='diaqnostikalarprices',
            name='qiymet',
            field=models.CharField(max_length=64, verbose_name='Adı'),
        ),
        migrations.AlterField(
            model_name='xidmetlerprices',
            name='qiymet',
            field=models.CharField(max_length=64, verbose_name='Qiymət'),
        ),
        migrations.AlterField(
            model_name='xidmetlerprices',
            name='xidmet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qiymetler', to='service.Xidmatlar', verbose_name='Xidmətin Adı'),
        ),
    ]
