# Generated by Django 2.1.2 on 2019-04-19 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0032_auto_20190419_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='address',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Klinika Ünvanı'),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='address_az',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Klinika Ünvanı'),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='address_ru',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Klinika Ünvanı'),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='name',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Klinika Adı'),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='name_az',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Klinika Adı'),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='name_ru',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Klinika Adı'),
        ),
    ]
