# Generated by Django 2.1.2 on 2019-04-25 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diaqnostikalar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DiaqnostikalarGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(blank=True, max_length=128, null=True, verbose_name='Diaqnostik Xidmət Qrupun Adı')),
            ],
        ),
        migrations.CreateModel(
            name='Xidmatlar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='XidmatlarGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(blank=True, max_length=128, null=True, verbose_name='Xidmət Qrup Adı')),
            ],
        ),
        migrations.AddField(
            model_name='xidmatlar',
            name='service_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='xidmetler', to='service.XidmatlarGroup', verbose_name='Xidmətin Adı'),
        ),
        migrations.AddField(
            model_name='diaqnostikalar',
            name='diaqnostika_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diaqnostikalar', to='service.DiaqnostikalarGroup', verbose_name='Diaqnostik Xidmətin Adı'),
        ),
    ]
