# Generated by Django 2.1.2 on 2019-03-03 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicecategroyname', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicegroupname', models.CharField(max_length=128)),
                ('servicecategory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_services', to='service.ServiceCategory')),
            ],
        ),
        migrations.AddField(
            model_name='service',
            name='servicegroup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_services', to='service.ServiceGroup'),
        ),
    ]
