# Generated by Django 2.1.2 on 2019-04-25 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diaqnostikalar',
            name='name_az',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='diaqnostikalar',
            name='name_ru',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='diaqnostikalargroup',
            name='group_name_az',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Diaqnostik Xidmət Qrupun Adı'),
        ),
        migrations.AddField(
            model_name='diaqnostikalargroup',
            name='group_name_ru',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Diaqnostik Xidmət Qrupun Adı'),
        ),
        migrations.AddField(
            model_name='xidmatlar',
            name='name_az',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='xidmatlar',
            name='name_ru',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='xidmatlargroup',
            name='group_name_az',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Xidmət Qrup Adı'),
        ),
        migrations.AddField(
            model_name='xidmatlargroup',
            name='group_name_ru',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Xidmət Qrup Adı'),
        ),
    ]
