# Generated by Django 2.1.2 on 2019-03-03 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='name',
        ),
        migrations.RemoveField(
            model_name='service',
            name='servicegroup',
        ),
        migrations.RemoveField(
            model_name='servicecategory',
            name='servicecategroyname',
        ),
        migrations.RemoveField(
            model_name='servicegroup',
            name='servicecategory',
        ),
        migrations.RemoveField(
            model_name='servicegroup',
            name='servicegroupname',
        ),
    ]
