# Generated by Django 2.1.2 on 2019-05-27 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_diaqnostika'),
    ]

    operations = [
        migrations.AddField(
            model_name='diaqnostika',
            name='name_az',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='diaqnostika',
            name='name_ru',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='xidmat',
            name='name_az',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='xidmat',
            name='name_ru',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
