# Generated by Django 2.1.2 on 2019-03-03 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_service_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='xidmet_category',
            field=models.CharField(blank=True, choices=[('XDM', 'xidmetler'), ('DQN', 'diaqnostika')], max_length=25, null=True),
        ),
    ]
