# Generated by Django 2.1.2 on 2019-03-03 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_service_xidmet_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='service_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='service.ServiceGroup'),
        ),
        migrations.AddField(
            model_name='servicegroup',
            name='group_name',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
