# Generated by Django 2.1.2 on 2019-03-03 22:23

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('clinic', '0007_auto_20190303_1412'),
        ('service', '0005_auto_20190303_1419'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Service',
            new_name='Xidmetler',
        ),
        migrations.RenameModel(
            old_name='ServiceGroup',
            new_name='XidmetlerGroup',
        ),
        migrations.DeleteModel(
            name='ServiceCategory',
        ),
    ]
