# Generated by Django 2.1.2 on 2019-03-03 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0008_auto_20190303_1430'),
        ('service', '0007_auto_20190303_1428'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='xidmatlar',
            name='service_group',
        ),
        migrations.DeleteModel(
            name='Xidmatlar',
        ),
    ]
