# Generated by Django 2.1.2 on 2019-03-03 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0008_auto_20190303_1430'),
    ]

    operations = [
        migrations.CreateModel(
            name='Xidmatlar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xidmet_category', models.CharField(blank=True, choices=[('XDM', 'xidmetler'), ('DQN', 'diaqnostika')], max_length=25, null=True)),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('service_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='service.XidmatlarGroup')),
            ],
        ),
    ]
