# Generated by Django 2.1.2 on 2019-03-03 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0010_auto_20190303_1503'),
    ]

    operations = [
        migrations.DeleteModel(
            name='XidmatlarGroup',
        ),
    ]
