# Generated by Django 2.1.2 on 2019-03-03 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('service', '0011_delete_xidmatlargroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='XidmatlarGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
    ]
