# Generated by Django 2.1.2 on 2019-03-03 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0013_xidmatlar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diaqnostikalar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DiaqnostikalarGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='xidmatlar',
            name='xidmet_category',
        ),
        migrations.AddField(
            model_name='diaqnostikalar',
            name='diaqnostika_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='service.DiaqnostikalarGroup'),
        ),
    ]
