# Generated by Django 2.1.2 on 2019-03-03 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0014_auto_20190303_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diaqnostikalar',
            name='diaqnostika_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diaqnostikalar', to='service.DiaqnostikalarGroup'),
        ),
        migrations.AlterField(
            model_name='xidmatlar',
            name='service_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='xidmetler', to='service.XidmatlarGroup'),
        ),
    ]
