# Generated by Django 2.1.2 on 2019-03-13 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0015_auto_20190303_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diaqnostikalar',
            name='name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='xidmatlar',
            name='name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
