# Generated by Django 2.1.2 on 2019-03-13 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0016_auto_20190313_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diaqnostikalargroup',
            name='group_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='xidmatlargroup',
            name='group_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
