# Generated by Django 2.1.2 on 2019-04-19 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0017_auto_20190313_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='diaqnostikalar',
            name='name_az',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='diaqnostikalar',
            name='name_ru',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='diaqnostikalargroup',
            name='group_name_az',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='diaqnostikalargroup',
            name='group_name_ru',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='xidmatlar',
            name='name_az',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='xidmatlar',
            name='name_ru',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='xidmatlargroup',
            name='group_name_az',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='xidmatlargroup',
            name='group_name_ru',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
