# Generated by Django 2.1.2 on 2019-04-25 22:22

import ckeditor.fields
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clinic', '0003_auto_20190425_1508'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicSaatlar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bzsaat', models.CharField(blank=True, max_length=64, null=True, verbose_name='bzsaat')),
                ('clinic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hekimler', to='clinic.Clinic', verbose_name='Clinic')),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Kişi'), ('F', 'Qadın')], max_length=25, null=True, verbose_name='Həkimin Cinsi')),
                ('first_name', models.CharField(blank=True, max_length=256, null=True, verbose_name='Həkimin Adı')),
                ('first_name_az', models.CharField(blank=True, max_length=256, null=True, verbose_name='Həkimin Adı')),
                ('first_name_ru', models.CharField(blank=True, max_length=256, null=True, verbose_name='Həkimin Adı')),
                ('last_name', models.CharField(blank=True, max_length=256, null=True, verbose_name='Həkimin Soyadı')),
                ('last_name_az', models.CharField(blank=True, max_length=256, null=True, verbose_name='Həkimin Soyadı')),
                ('last_name_ru', models.CharField(blank=True, max_length=256, null=True, verbose_name='Həkimin Soyadı')),
                ('title', models.CharField(blank=True, max_length=256, null=True, verbose_name='Həkimin titulu')),
                ('title_az', models.CharField(blank=True, max_length=256, null=True, verbose_name='Həkimin titulu')),
                ('title_ru', models.CharField(blank=True, max_length=256, null=True, verbose_name='Həkimin titulu')),
                ('tecrube', models.IntegerField(blank=True, null=True, verbose_name='Həkimin Təcrübəsi')),
                ('contact_phone', models.CharField(blank=True, max_length=256, null=True, verbose_name='Qəbul Üçün Telefon')),
                ('qebula_yazilma', models.CharField(blank=True, max_length=256, null=True, verbose_name='Həkimin Qəbulu Qiyməti')),
                ('qebula_yazilma_endirim_faiz', models.CharField(blank=True, max_length=256, null=True, verbose_name='Həkim Qəbulu Endirim %-lə')),
                ('image', models.ImageField(blank=True, default='defaultdoctor.png', null=True, upload_to='', verbose_name='Profil Şəkli')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Həkim Haqqında Ətraflı Məlumat')),
                ('description_az', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Həkim Haqqında Ətraflı Məlumat')),
                ('description_ru', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Həkim Haqqında Ətraflı Məlumat')),
                ('clinic', models.ManyToManyField(blank=True, null=True, related_name='doctors', to='clinic.Clinic', verbose_name='İşlədiyi Klinikalar')),
            ],
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, null=True, verbose_name='İxtisas adı')),
                ('name_az', models.CharField(blank=True, max_length=256, null=True, verbose_name='İxtisas adı')),
                ('name_ru', models.CharField(blank=True, max_length=256, null=True, verbose_name='İxtisas adı')),
                ('description', models.TextField(blank=True, max_length=10000, null=True, verbose_name='Qısa Məlumat')),
                ('description_az', models.TextField(blank=True, max_length=10000, null=True, verbose_name='Qısa Məlumat')),
                ('description_ru', models.TextField(blank=True, max_length=10000, null=True, verbose_name='Qısa Məlumat')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('star', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('message', models.TextField(blank=True, max_length=4000, null=True)),
                ('published', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('clinic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clinic.Clinic')),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='doctor.Doctor')),
                ('starter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sertifikat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sertifikatlar', to='doctor.Doctor')),
            ],
        ),
        migrations.AddField(
            model_name='doctor',
            name='professions',
            field=models.ManyToManyField(blank=True, null=True, related_name='doctors', to='doctor.Profession', verbose_name='Həkimin İxtisasları'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='wishlist',
            field=models.ManyToManyField(blank=True, null=True, related_name='wishlist', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clinicsaatlar',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='doctor.Doctor'),
        ),
    ]
