# Generated by Django 2.1 on 2018-09-09 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='wishlist',
            field=models.ManyToManyField(related_name='wishlist', to='doctor.Profession'),
        ),
    ]
