# Generated by Django 2.1.2 on 2019-03-10 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profession',
            name='description',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
    ]
