# Generated by Django 2.1.2 on 2019-05-29 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicsaatlar',
            name='evde_muayine',
            field=models.BooleanField(blank=True, null=True, verbose_name='Evdə müayinə'),
        ),
        migrations.AddField(
            model_name='clinicsaatlar',
            name='evde_muayine_endirim_faiz',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Evdə Müayinə Endirim %-lə'),
        ),
        migrations.AddField(
            model_name='clinicsaatlar',
            name='evde_muayine_qiymet',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Evdə Müayinə Qiyməti'),
        ),
        migrations.AddField(
            model_name='clinicsaatlar',
            name='qebula_yazilma',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Həkimin Qəbulu Qiyməti'),
        ),
        migrations.AddField(
            model_name='clinicsaatlar',
            name='qebula_yazilma_endirim_faiz',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Həkim Qəbulu Endirim %-lə'),
        ),
        migrations.AddField(
            model_name='clinicsaatlar',
            name='usaq_hekimi',
            field=models.BooleanField(blank=True, null=True, verbose_name='Uşaq həkimi?'),
        ),
        migrations.AddField(
            model_name='clinicsaatlar',
            name='usaq_hekimi_endirim_faiz',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Uşaq həkimi Endirim %-lə'),
        ),
        migrations.AddField(
            model_name='clinicsaatlar',
            name='usaq_hekimi_qiymet',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Uşaq Həkimi Müayinə Qiyməti'),
        ),
    ]
