# Generated by Django 2.1.2 on 2019-05-29 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_auto_20190529_0719'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='evde_muayine',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='evde_muayine_endirim_faiz',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='evde_muayine_qiymet',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='qebula_yazilma',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='qebula_yazilma_endirim_faiz',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='usaq_hekimi',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='usaq_hekimi_endirim_faiz',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='usaq_hekimi_qiymet',
        ),
    ]
