# Generated by Django 2.1 on 2018-09-09 12:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_doctor_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='wishlist',
            field=models.ManyToManyField(related_name='wishlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
