# Generated by Django 2.1.2 on 2019-02-10 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_auto_20180927_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
