# Generated by Django 2.1.2 on 2019-04-26 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_auto_20190425_1523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinicsaatlar',
            name='bzsaat',
        ),
        migrations.AddField(
            model_name='clinicsaatlar',
            name='be_cm_issaati',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='BE - Cümə İş Saatı'),
        ),
        migrations.AddField(
            model_name='clinicsaatlar',
            name='bz_issaati',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Bazar İş Saatı'),
        ),
        migrations.AddField(
            model_name='clinicsaatlar',
            name='sn_issaati',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Şənbə İş Saatı'),
        ),
    ]
