# Generated by Django 2.1.2 on 2019-04-26 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_auto_20190426_0039'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='evde_muayine',
            field=models.BooleanField(blank=True, null=True, verbose_name='Evdə müayinə'),
        ),
    ]
