# Generated by Django 2.1.2 on 2019-02-11 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_clinic_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='clinics',
            field=models.ManyToManyField(related_name='doctors', to='clinic.Clinic'),
        ),
        migrations.AlterField(
            model_name='review',
            name='clinic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='clinic.Clinic'),
        ),
        migrations.DeleteModel(
            name='Clinic',
        ),
    ]
