# Generated by Django 2.1 on 2018-09-09 12:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_auto_20180909_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='wishlist',
            field=models.ManyToManyField(null=True, related_name='wishlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
