# Generated by Django 2.1.2 on 2019-04-04 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0004_auto_20190321_0358'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='title',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
