# Generated by Django 2.1.2 on 2019-04-26 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0004_doctor_evde_muayine'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='evde_muayine_qiymet',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Evdə Müayinə Qiyməti'),
        ),
    ]
