# Generated by Django 2.1.2 on 2019-02-13 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0004_auto_20190211_0237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='star',
        ),
    ]
