# Generated by Django 2.1.2 on 2019-04-05 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0027_auto_20190404_1721'),
        ('doctor', '0005_doctor_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='clinic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clinic.Clinic'),
        ),
    ]
