# Generated by Django 2.1.2 on 2019-02-13 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0005_remove_review_star'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='clinic',
        ),
    ]
