# Generated by Django 2.1.2 on 2019-04-19 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0006_review_clinic'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='first_name_en',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='first_name_ru',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='last_name_en',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='last_name_ru',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
