# Generated by Django 2.1.2 on 2019-04-26 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0006_auto_20190426_0147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurancepackage',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hekimler', to='insurance.Company', verbose_name='Company'),
        ),
    ]
