# Generated by Django 2.1.2 on 2019-04-26 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0007_auto_20190426_0152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insurancepackage',
            name='company',
        ),
        migrations.RemoveField(
            model_name='insurancepackage',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='company',
        ),
        migrations.DeleteModel(
            name='InsurancePackage',
        ),
    ]
