# Generated by Django 2.1.2 on 2019-02-13 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0007_review_star'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='published',
            field=models.TextField(max_length=4000, null=True),
        ),
    ]
