# Generated by Django 2.1.2 on 2019-04-19 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0008_auto_20190419_1359'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='city',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='city',
            name='country',
        ),
        migrations.DeleteModel(
            name='City',
        ),
    ]
