# Generated by Django 2.1.2 on 2019-02-13 15:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0008_review_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='published',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
    ]
