# Generated by Django 2.1.2 on 2019-04-19 22:44

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0009_auto_20190419_1513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sertifikat',
            name='name',
        ),
        migrations.AddField(
            model_name='doctor',
            name='description_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='description_ru',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='title_en',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='title_ru',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='profession',
            name='description_en',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='profession',
            name='description_ru',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='profession',
            name='name_en',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='profession',
            name='name_ru',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='first_name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='first_name_en',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='first_name_ru',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='last_name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='last_name_en',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='last_name_ru',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='professions',
            field=models.ManyToManyField(blank=True, null=True, related_name='doctors', to='doctor.Profession'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='qebula_yazilma',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='qebula_yazilma_endirim_faiz',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='tecrube',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profession',
            name='name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
