# Generated by Django 2.1.2 on 2019-02-20 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0013_delete_xidmetler_qiymet'),
        ('doctor', '0009_auto_20190213_0723'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='clinicsbranch',
            field=models.ManyToManyField(related_name='doctors', to='clinic.Clinic_branch'),
        ),
    ]
