# Generated by Django 2.1.2 on 2019-04-28 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0009_auto_20190426_0208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insurancepackage',
            name='packages',
        ),
    ]
