# Generated by Django 2.1.2 on 2019-04-28 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0010_remove_insurancepackage_packages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinicsaatlar',
            name='be_cm_issaati',
        ),
        migrations.AddField(
            model_name='clinicsaatlar',
            name='bes_issaati',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='5-ci gün  İş Saatı'),
        ),
        migrations.AddField(
            model_name='clinicsaatlar',
            name='bir_issaati',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='1-ci gün İş Saatı'),
        ),
        migrations.AddField(
            model_name='clinicsaatlar',
            name='dord_issaati',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='4-ci gün  İş Saatı'),
        ),
        migrations.AddField(
            model_name='clinicsaatlar',
            name='iki_issaati',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='2-ci gün İş Saatı'),
        ),
        migrations.AddField(
            model_name='clinicsaatlar',
            name='uc_issaati',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='3-ci gün  İş Saatı'),
        ),
    ]
