# Generated by Django 2.1.2 on 2019-04-19 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0010_auto_20190419_1544'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='description_ru',
            new_name='description_az',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='first_name_ru',
            new_name='first_name_az',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='last_name_ru',
            new_name='last_name_az',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='title_ru',
            new_name='title_az',
        ),
        migrations.RenameField(
            model_name='profession',
            old_name='description_ru',
            new_name='description_az',
        ),
        migrations.RemoveField(
            model_name='profession',
            name='name_ru',
        ),
        migrations.AddField(
            model_name='profession',
            name='name_az',
            field=models.CharField(default='İxtisas Adı', max_length=256, null=True, verbose_name='İxtisas adı'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='professions',
            field=models.ManyToManyField(related_name='doctors', to='doctor.Profession'),
        ),
        migrations.AlterField(
            model_name='profession',
            name='name',
            field=models.CharField(default='İxtisas Adı', max_length=256, verbose_name='İxtisas adı'),
        ),
        migrations.AlterField(
            model_name='profession',
            name='name_en',
            field=models.CharField(default='İxtisas Adı', max_length=256, null=True, verbose_name='İxtisas adı'),
        ),
    ]
