# Generated by Django 2.1.2 on 2019-04-19 23:02

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0011_auto_20190419_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='clinics',
            field=models.ManyToManyField(related_name='doctors', to='clinic.Clinic', verbose_name='İşlədiyi Klinikalar'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Qəbul Üçün Telefon'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Həkim Haqqında Ətraflı Məlumat'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='description_az',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Həkim Haqqında Ətraflı Məlumat'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='description_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Həkim Haqqında Ətraflı Məlumat'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='first_name',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Həkimin Adı'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='first_name_az',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Həkimin Adı'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='first_name_en',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Həkimin Adı'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Kişi'), ('F', 'Qadın')], max_length=25, null=True, verbose_name='Həkimin Cinsi'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Profil Şəkli'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='last_name',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Həkimin Soyadı'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='last_name_az',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Həkimin Soyadı'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='last_name_en',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Həkimin Soyadı'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='professions',
            field=models.ManyToManyField(related_name='doctors', to='doctor.Profession', verbose_name='Həkimin İxtisasları'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='qebula_yazilma',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Həkimin Qəbulu Qiyməti'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='qebula_yazilma_endirim_faiz',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Həkim Qəbulu Endirim %-lə'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='tecrube',
            field=models.IntegerField(blank=True, null=True, verbose_name='Həkimin Təcrübəsi'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='title',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Həkimin titulu'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='title_az',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Həkimin titulu'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='title_en',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Həkimin titulu'),
        ),
        migrations.AlterField(
            model_name='profession',
            name='description',
            field=models.TextField(blank=True, max_length=10000, null=True, verbose_name='Qısa Məlumat'),
        ),
        migrations.AlterField(
            model_name='profession',
            name='description_az',
            field=models.TextField(blank=True, max_length=10000, null=True, verbose_name='Qısa Məlumat'),
        ),
        migrations.AlterField(
            model_name='profession',
            name='description_en',
            field=models.TextField(blank=True, max_length=10000, null=True, verbose_name='Qısa Məlumat'),
        ),
    ]
