# Generated by Django 2.1.2 on 2019-04-19 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0012_auto_20190419_1602'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='description_en',
            new_name='description_ru',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='first_name_en',
            new_name='first_name_ru',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='last_name_en',
            new_name='last_name_ru',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='title_en',
            new_name='title_ru',
        ),
        migrations.RenameField(
            model_name='profession',
            old_name='description_en',
            new_name='description_ru',
        ),
        migrations.RenameField(
            model_name='profession',
            old_name='name_en',
            new_name='name_ru',
        ),
    ]
